<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('menus')->truncate();

        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => 'Dashboard',
                'route' => '/',
                'icon' => 'LayoutDashboard',
                'parent_id' => null,
                'permission_id' => null,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Gestão de Usuários',
                'route' => '/users',
                'icon' => 'Users',
                'parent_id' => null,
                'permission_id' => 1,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 3,
                'name' => 'Gestão Acadêmica',
                'route' => null,
                'icon' => 'Book',
                'parent_id' => null,
                'permission_id' => null,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 4,
                'name' => 'Planos de Assinatura',
                'route' => '/plans',
                'icon' => 'CreditCard',
                'parent_id' => 3,
                'permission_id' => null,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 5,
                'name' => 'Gestão de Aulas',
                'route' => '/class',
                'icon' => 'Calendar',
                'parent_id' => 3,
                'permission_id' => null,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 6,
                'name' => 'Relatórios',
                'route' => '/report',
                'icon' => 'FileDown',
                'parent_id' => null,
                'permission_id' => 12,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 7,
                'name' => 'Administração',
                'route' => null,
                'icon' => 'Settings',
                'parent_id' => null,
                'permission_id' => null,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 8,
                'name' => 'Cadastros',
                'route' => null,
                'icon' => null,
                'parent_id' => 7,
                'permission_id' => null,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 9,
                'name' => 'Tipos de Documento',
                'route' => '/settings/document-types',
                'icon' => null,
                'parent_id' => 8,
                'permission_id' => 10,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 10,
                'name' => 'Perfis de Usuário',
                'route' => '/settings/user-types',
                'icon' => null,
                'parent_id' => 8,
                'permission_id' => 2,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 11,
                'name' => 'Estados',
                'route' => '/settings/states',
                'icon' => null,
                'parent_id' => 8,
                'permission_id' => 5,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 12,
                'name' => 'Cidades',
                'route' => '/settings/city',
                'icon' => null,
                'parent_id' => 8,
                'permission_id' => 7,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 13,
                'name' => 'Controle de Acesso',
                'route' => null,
                'icon' => null,
                'parent_id' => 7,
                'permission_id' => null,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 14,
                'name' => 'Perfil de Acesso',
                'route' => '/settings/user-type-permissions',
                'icon' => null,
                'parent_id' => 13,
                'permission_id' => 14,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 15,
                'name' => 'Permissões',
                'route' => '/settings/permissions',
                'icon' => null,
                'parent_id' => 13,
                'permission_id' => 13,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 16,
                'name' => 'Auditoria',
                'route' => '/audit',
                'icon' => 'History',
                'parent_id' => null,
                'permission_id' => 4,
                'order' => 0,
                'visible' => 1,
            ],
            [
                'id' => 17,
                'name' => 'Menu',
                'route' => '/settings/menus',
                'icon' => null,
                'parent_id' => 8,
                'permission_id' => 15,
                'order' => 0,
                'visible' => 1,
            ],
        ]);
    }
}
